[package]
name = "nyaterm-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
crypto_secretbox.workspace = true
dirs.workspace = true
encoding_rs.workspace = true
futures.workspace = true
nyaterm-mcp-protocol.workspace = true
hex.workspace = true
hmac.workspace = true
md5.workspace = true
percent-encoding.workspace = true
quick-xml.workspace = true
rand.workspace = true
regex.workspace = true
rusty-leveldb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
url.workspace = true
unicode-normalization.workspace = true
unicode-segmentation.workspace = true
uuid.workspace = true
zeroize.workspace = true
zip.workspace = true
